### ISSUE TITLE
[Question] Can I use your code in a mod?

### ISSUE THREAD

**Issue by Oliver-makes-code** [lucaargolo/structure-world#4]
Hey! I'm working on a mod for 1.18 that replaces the world with a Tree, would it be cool if I used some of your code in it? (With proper credit, of course)
Thanks!

**Comment by lucaargolo** [comment]
Yes, you can, just be sure to check the license and see what you can and what you cannot do.  Your project will also have to be open source and files from this mod will maintain the same license I'm using. Though I don't really know how that works when you edit the file or only use parts of the code.
